// List of all Dota 2 heroes with their IDs for CDN integration
export const DOTA_HEROES = [
  { id: 1, name: 'Anti-Mage', apiId: 1 },
  { id: 2, name: 'Axe', apiId: 2 },
  { id: 3, name: 'Bane', apiId: 3 },
  { id: 4, name: 'Bloodseeker', apiId: 4 },
  { id: 5, name: 'Brown Eft', apiId: 5 },
  { id: 6, name: 'Crystal Maiden', apiId: 6 },
  { id: 7, name: 'Drow Ranger', apiId: 7 },
  { id: 8, name: 'Earthshaker', apiId: 8 },
  { id: 9, name: 'Juggernaut', apiId: 9 },
  { id: 10, name: 'Mirana', apiId: 10 },
  { id: 11, name: 'Morphling', apiId: 11 },
  { id: 12, name: 'Shadow Fiend', apiId: 12 },
  { id: 13, name: 'Phantom Lancer', apiId: 13 },
  { id: 14, name: 'Puck', apiId: 14 },
  { id: 15, name: 'Pudge', apiId: 15 },
  { id: 16, name: 'Razor', apiId: 16 },
  { id: 17, name: 'Sand King', apiId: 17 },
  { id: 18, name: 'Storm Spirit', apiId: 18 },
  { id: 19, name: 'Sven', apiId: 19 },
  { id: 20, name: 'Tiny', apiId: 20 },
  { id: 21, name: 'Vengeful Spirit', apiId: 21 },
  { id: 22, name: 'Windranger', apiId: 22 },
  { id: 23, name: 'Zeus', apiId: 23 },
  { id: 24, name: 'Silencer', apiId: 24 },
  { id: 25, name: 'Ancient Apparition', apiId: 25 },
  { id: 26, name: 'Bristleback', apiId: 26 },
  { id: 27, name: 'Tusk', apiId: 27 },
  { id: 28, name: 'Skywrath Mage', apiId: 28 },
  { id: 29, name: 'Abaddon', apiId: 29 },
  { id: 30, name: 'Elder Titan', apiId: 30 },
  { id: 31, name: 'Faceless Void', apiId: 31 },
  { id: 32, name: 'Spirit Breaker', apiId: 32 },
  { id: 33, name: 'Techies', apiId: 33 },
  { id: 34, name: 'Ogre Magi', apiId: 34 },
  { id: 35, name: 'Undying', apiId: 35 },
  { id: 36, name: 'Rubick', apiId: 36 },
  { id: 37, name: 'Disruptor', apiId: 37 },
  { id: 38, name: 'Death Prophet', apiId: 38 },
  { id: 39, name: 'Phantom Assassin', apiId: 39 },
  { id: 40, name: 'Pugna', apiId: 40 },
  { id: 41, name: 'Templar Assassin', apiId: 41 },
  { id: 42, name: 'Viper', apiId: 42 },
  { id: 43, name: 'Wraith King', apiId: 43 },
  { id: 44, name: 'Riki', apiId: 44 },
  { id: 45, name: 'Weaver', apiId: 45 },
  { id: 46, name: 'Witch Doctor', apiId: 46 },
  { id: 47, name: 'Queen of Pain', apiId: 47 },
  { id: 48, name: 'Enchantress', apiId: 48 },
  { id: 49, name: 'Treant Protector', apiId: 49 },
  { id: 50, name: 'Observer Ward', apiId: 50 },
  { id: 51, name: 'Centaur Warrunner', apiId: 51 },
  { id: 52, name: 'Magnataur', apiId: 52 },
  { id: 53, name: 'Timbersaw', apiId: 53 },
  { id: 54, name: 'Medusa', apiId: 54 },
  { id: 55, name: 'Troll Warlord', apiId: 55 },
  { id: 56, name: 'Dire', apiId: 56 },
  { id: 57, name: 'Naga Siren', apiId: 57 },
  { id: 58, name: 'Bounty Hunter', apiId: 58 },
  { id: 59, name: 'Invoker', apiId: 59 },
  { id: 60, name: 'Outworld Destroyer', apiId: 60 },
  { id: 61, name: 'Lifestealer', apiId: 61 },
  { id: 62, name: 'Dark Seer', apiId: 62 },
  { id: 63, name: 'Clinkz', apiId: 63 },
  { id: 64, name: 'Omniknight', apiId: 64 },
  { id: 65, name: 'Enchantress', apiId: 65 },
  { id: 66, name: 'Huskar', apiId: 66 },
  { id: 67, name: 'Night Stalker', apiId: 67 },
  { id: 68, name: 'Broodmother', apiId: 68 },
  { id: 69, name: 'Bounty Hunter', apiId: 69 },
  { id: 70, name: 'Ursa', apiId: 70 },
  { id: 71, name: 'Gyrocopter', apiId: 71 },
  { id: 72, name: 'Alchemist', apiId: 72 },
  { id: 73, name: 'Doom', apiId: 73 },
  { id: 74, name: 'Tidehunter', apiId: 74 },
  { id: 75, name: 'Kunkka', apiId: 75 },
  { id: 76, name: 'Modifying hero', apiId: 76 },
  { id: 77, name: 'Warlock', apiId: 77 },
  { id: 78, name: 'Monkeyking', apiId: 78 },
  { id: 79, name: 'Dragon Knight', apiId: 79 },
  { id: 80, name: 'Dazzle', apiId: 80 },
  { id: 81, name: 'Clockwerk', apiId: 81 },
  { id: 82, name: 'Leshrac', apiId: 82 },
  { id: 83, name: 'Nature\'s Prophet', apiId: 83 },
  { id: 84, name: 'Lifestealer', apiId: 84 },
  { id: 85, name: 'Dark Willow', apiId: 85 },
  { id: 86, name: 'Pangolier', apiId: 86 },
  { id: 87, name: 'Grimstroke', apiId: 87 },
  { id: 88, name: 'Void Spirit', apiId: 88 },
];

// Simplified hero list for display
export const POPULAR_HEROES = [
  'Axe', 'Crystal Maiden', 'Drow Ranger', 'Earthshaker', 'Juggernaut',
  'Mirana', 'Morphling', 'Shadow Fiend', 'Phantom Lancer', 'Puck',
  'Pudge', 'Storm Spirit', 'Sven', 'Tiny', 'Windranger', 'Zeus',
  'Anti-Mage', 'Bounty Hunter', 'Broodmother', 'Centaur Warrunner',
  'Clinkz', 'Dark Seer', 'Disruptor', 'Doom', 'Dragon Knight',
  'Invoker', 'Lifestealer', 'Medusa', 'Rubick', 'Sand King',
];

// Get hero image URL from CDN
export function getHeroImageUrl(heroName) {
  // Using Stratz CDN for hero images
  const cleanName = heroName.toLowerCase().replace(/['\s]/g, '-');
  return `https://cdn.stratz.com/images/dota2/heroes/hero_${cleanName}_lg.png`;
}

// Fallback: Use a generic placeholder
export function getHeroPlaceholder() {
  return 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="200" height="200"%3E%3Crect fill="%231a1a1a" width="200" height="200"/%3E%3Ctext x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="%23d4af37" font-size="14" font-family="sans-serif"%3EHero Image%3C/text%3E%3C/svg%3E';
}
